### ISSUE TITLE
“Push Notifications” will damage your computer. You should move it to the Trash.

### ISSUE THREAD

**Issue by wenhw** [onmyway133/PushNotifications#37] opened 2020-04-22 06:33 UTC
![image](https://user-images.githubusercontent.com/1060948/79948343-4711ae00-84a6-11ea-93b7-35e70f328bac.png)

**Comment by Ariandr** [comment] 2020-04-22 06:54
Please, install the latest release, this crash is fixed there.

**Comment by Ariandr** [comment] 2020-04-22 10:09
Closing the issue, it's a duplicate of https://github.com/onmyway133/PushNotifications/issues/35

**Closed by Ariandr** 2020-04-22 10:09 UTC
